[WIP] Moving/improving code from other projects + initial setup
RackSec/dwarf pull request #2
Opened 2018-01-24 16:23 UTC by smogg

2018-01-24 18:31 UTC, irinarenteria requested changes

2018-01-24 18:31 UTC, irinarenteria commented on README.md
> +redefined function was called in its body. If it wasn't it would report a test
Proofreading: "If it wasn't, it would report..."

2018-01-24 18:31 UTC, irinarenteria commented on src/dwarf/dates.cljc
> +  (:require #?(:clj [clj-time.coerce :as tco]
Why do we need `#?` here?

2018-01-24 18:31 UTC, irinarenteria commented on README.md
> +(format-date "2016-09-07T11:17:13.090Z") ;=> "2016-09-07""
There are extra quotation marks on lines 87 and 88.

2018-01-24 18:31 UTC, irinarenteria commented on README.md
> +```
Looks like `parse-date` has functionalities not shown here. Let's add examples for all of them.

2018-01-24 18:31 UTC, irinarenteria commented on src/dwarf/test.cljc
> +(ns dwarf.test
What do you think about calling this `mock` instead of `test`? It might create unnecessary confusion when importing the lib or reading through the tests for this namespace.

2018-01-24 18:31 UTC, irinarenteria commented on test/dwarf/dates_test.cljc
> +(deftest parse-date-test
I'm not sure if this is a convention, but it would be more readable to name the test fns as `test-my-fn` vs `my-fn-test`.

2018-01-24 18:42 UTC, smogg commented on README.md
> +```
I'm sorry, but what functionalities are we talking about?

2018-01-24 18:44 UTC, smogg commented on src/dwarf/dates.cljc
> +  (:require #?(:clj [clj-time.coerce :as tco]
This is a _reader-conditional_. Since this is a file shared between clj/cljs, this is like saying "do what's under :clj when inside Clojure, do what's under :cljs key when inside ClojureScript)

2018-01-24 18:45 UTC, smogg commented on src/dwarf/test.cljc
> +(ns dwarf.test
Yes - the `test-test` namespace was annoying :P

2018-01-24 18:47 UTC, smogg commented on test/dwarf/dates_test.cljc
> +(deftest parse-date-test
Hmm... It's a personal thing, but I honestly thing the code is more readable when the `-test` is at the end - I already know it's a test since it's next to a `deftest`.
I'm following a convention mentioned here: https://github.com/bbatsov/clojure-style-guide#testing and what I saw in most Clojure projects online.

2018-01-24 18:48 UTC, smogg commented on README.md
> +(format-date "2016-09-07T11:17:13.090Z") ;=> "2016-09-07""
Stupid machines trying to be helpful.

2018-01-25 16:40 UTC, sirsean requested changes
I find myself wondering why this has both mocking test helper functions and date functions, but maybe that makes sense if `dwarf` is a cross-platform helper library.

I have some notes about the date functions, two of which seem very similar to the point that I can't tell why we don't have just one of them.

It seems like it's hard to test `with-redef-calls`. I assume you've tried it in both clj and cljs?

2018-01-25 16:40 UTC, sirsean commented on src/dwarf/dates.cljc
> +   (when-not (nil? date)
We probably want a nil check for `formatter` also.

```
=> (tf/unparse nil (tc/now))
NullPointerException   clj-time.format/unparse (format.clj:204)
```

2018-01-25 16:40 UTC, sirsean commented on src/dwarf/dates.cljc
> +(defn format-date
The difference between `unparse-date` and `format-date` seems kind of unclear to me. Why do we need both, and why would someone use one instead of the other? (Is it possible to combine both functions into one?)

2018-01-25 16:41 UTC, sirsean commented on src/dwarf/dates.cljc
> +  (:require #?(:clj [clj-time.coerce :as tco]
You'll only need this for `cljc` files, but it's a good thing to have seen. 😄

2018-01-25 16:45 UTC, sirsean commented on test/dwarf/dates_test.cljc
> +(deftest parse-date-test
As a matter of taste, I agree with irina. Plus, when I'm running a single test from the command line, it's easier to edit which test is being called if `test-` is prepended rather than `-test` being appended. (Because changing the function name requires 5-10 fewer button presses.)

```
lein test :only things.todo-test/do-thing-test
lein test :only things.todo-test/other-thing-test

# doing it this way is slightly faster to change, in case fractions of a second
# are as important to you as they are to me
lein test :only things.todo-test/test-do-thing
lein test :only things.todo-test/test-other-thing
```

But this matters very little, and I don't think it should hold us up.

2018-01-25 18:40 UTC, smogg commented on test/dwarf/dates_test.cljc
> +(deftest parse-date-test
Two to one so I'll make the proposed change :)

2018-01-25 18:42 UTC, smogg commented on src/dwarf/dates.cljc
> +(defn format-date
Doh, good point.

2018-01-25 18:55 UTC, smogg commented
`with-redef-calls` tests are passing both in Clj and Cljs, yes.

I've made all the changes request, thanks for the feedback!

2018-01-26 21:19 UTC, sirsean approved these changes

2018-01-29 17:20 UTC, irinarenteria commented on README.md
> +```
I mean that it looks like we can pass several kinds of formats and it would be useful to have them in the README:

```clojure
user=> (parse-date "10/31/2016")
#object[org.joda.time.DateTime 0x10d10130 "2016-10-31T00:00:00.000Z"]

user=> (parse-date "2016-9-2")
#object[org.joda.time.DateTime 0x77979057 "2016-09-02T00:00:00.000Z"]

user=> (parse-date "2016-01-02 03:04:05")
#object[org.joda.time.DateTime 0x6080252f "2016-01-02T03:04:05.000Z"]

user=> (parse-date "2016-01-02T03:04:05")
#object[org.joda.time.DateTime 0x2a65659f "2016-01-02T03:04:05.000Z"]

user=> (parse-date "2014-10-05T14:15:16.988Z")
#object[org.joda.time.DateTime 0x3d3e6a04 "2014-10-05T14:15:16.988Z"]

user=> (parse-date "2014-10-05 14:15:16.988Z")
#object[org.joda.time.DateTime 0x36efde7d "2014-10-05T14:15:16.988Z"]
```
It's not a huge deal, but would rather document it well to begin with.

2018-01-29 17:38 UTC, smogg commented on README.md
> +```
I pointed out in the readme that one should look at the source (since I'm quite sure people will forget about updating readme every time they make a change there anyway :P). But I have no problem with putting it there, thanks!

2018-01-29 17:41 UTC, irinarenteria commented on README.md
> +```
Thank you, @smogg 🎉

2018-01-29 17:42 UTC, irinarenteria approved these changes

2018-01-29 17:45 UTC, merged